import { Permissions } from 'oceanic.js';

export default {
    [Permissions.CREATE_INSTANT_INVITE.toString()]:               'Create Invite',
    [Permissions.KICK_MEMBERS.toString()]:                        'Kick Members',
    [Permissions.BAN_MEMBERS.toString()]:                         'Ban Members',
    [Permissions.ADMINISTRATOR.toString()]:                       'Administrator',
    [Permissions.MANAGE_CHANNELS.toString()]:                     'Manage Channels',
    [Permissions.MANAGE_GUILD.toString()]:                        'Manage Server',
    [Permissions.ADD_REACTIONS.toString()]:                       'Add Reactions',
    [Permissions.VIEW_AUDIT_LOG.toString()]:                      'View Audit Log',
    [Permissions.PRIORITY_SPEAKER.toString()]:                    'Priority Speaker',
    [Permissions.STREAM.toString()]:                              'Stream',
    [Permissions.VIEW_CHANNEL.toString()]:                        'View Channel',
    [Permissions.SEND_MESSAGES.toString()]:                       'Send Messages',
    [Permissions.SEND_TTS_MESSAGES.toString()]:                   'Send TTS Messages',
    [Permissions.MANAGE_MESSAGES.toString()]:                     'Manage Messages',
    [Permissions.EMBED_LINKS.toString()]:                         'Embed Links',
    [Permissions.ATTACH_FILES.toString()]:                        'Attach Files',
    [Permissions.READ_MESSAGE_HISTORY.toString()]:                'Read Message History',
    [Permissions.MENTION_EVERYONE.toString()]:                    'Mention Everyone',
    [Permissions.USE_EXTERNAL_EMOJIS.toString()]:                 'Use External Emojis',
    [Permissions.VIEW_GUILD_INSIGHTS.toString()]:                 'View Server Insights',
    [Permissions.CONNECT.toString()]:                             'Connect',
    [Permissions.SPEAK.toString()]:                               'Speak',
    [Permissions.MUTE_MEMBERS.toString()]:                        'Mute Members',
    [Permissions.DEAFEN_MEMBERS.toString()]:                      'Deafen Members',
    [Permissions.MOVE_MEMBERS.toString()]:                        'Move Members',
    [Permissions.USE_VAD.toString()]:                             'Use Voice Activity',
    [Permissions.CHANGE_NICKNAME.toString()]:                     'Change Nickname',
    [Permissions.MANAGE_NICKNAMES.toString()]:                    'Manage Nicknames',
    [Permissions.MANAGE_ROLES.toString()]:                        'Manage Roles',
    [Permissions.MANAGE_WEBHOOKS.toString()]:                     'Manage Webhooks',
    [Permissions.MANAGE_GUILD_EXPRESSIONS.toString()]:            'Manage Server Expressions',
    [Permissions.USE_APPLICATION_COMMANDS.toString()]:            'Use Application Commands',
    [Permissions.REQUEST_TO_SPEAK.toString()]:                    'Request To Speak',
    [Permissions.MANAGE_EVENTS.toString()]:                       'Manage Events',
    [Permissions.MANAGE_THREADS.toString()]:                      'Manage Threads',
    [Permissions.CREATE_PUBLIC_THREADS.toString()]:               'Create Public Threads',
    [Permissions.CREATE_PRIVATE_THREADS.toString()]:              'Create Private Threads',
    [Permissions.USE_EXTERNAL_STICKERS.toString()]:               'Use External Stickers',
    [Permissions.SEND_MESSAGES_IN_THREADS.toString()]:            'Send Messages In Threads',
    [Permissions.USE_EMBEDDED_ACTIVITIES.toString()]:             'Use Embedded Activities',
    [Permissions.MODERATE_MEMBERS.toString()]:                    'Timeout Members',
    [Permissions.VIEW_CREATOR_MONETIZATION_ANALYTICS.toString()]: 'View Monetization Analytics',
    [Permissions.USE_SOUNDBOARD.toString()]:                      'Use Soundboard',
    [Permissions.CREATE_GUILD_EXPRESSIONS.toString()]:            'Create Server Expressions',
    [Permissions.CREATE_EVENTS.toString()]:                       'Create Events',
    [Permissions.USE_EXTERNAL_SOUNDS.toString()]:                 'Use External Sounds',
    [Permissions.SEND_VOICE_MESSAGES.toString()]:                 'Send Voice Messages',
    [Permissions.USE_CLYDE_AI.toString()]:                        'Use Clyde AI',
    [Permissions.SET_VOICE_CHANNEL_STATUS.toString()]:            'Set Voice Channel Status',
}